GOOGLE_API_KEY = "AIzaSyAj4ajDsjA81JK-KB1xXajqgVrCXEkcNrg"
DB_HOST = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
DB_PORT = 4000
DB_USER = "msxT6kc8X9nFCmn.root"
DB_PASSWORD = "bBWK8vdCLlEBOFen"
DB_NAME = "vector_db"
